services:
    drawio-converter-base:
        build:
            context: ./drawio-converter-base
            dockerfile: Dockerfile
        image: mhoelzl/clx-drawio-converter-base:0.0.3
    notebook-processor-base:
        build:
            context: ./notebook-processor-base
            dockerfile: Dockerfile
        image: mhoelzl/clx-notebook-processor-base:0.0.3
    plantuml-converter-base:
        build:
            context: ./plantuml-converter-base
            dockerfile: Dockerfile
        image: mhoelzl/clx-plantuml-converter-base:0.0.3
